In [257]:
# !pip install transliterate
# !pip install openpyxl

In [258]:
import pandas as pd
import glob
import os
import numpy as np

In [259]:
df = pd.read_csv('zoki_liga_final.csv')

In [260]:
df.head(5)

,Број на играчи,Име,Позиција,Број на натпревари,Голови,Асистенции,Г/А,Г/А на натпревар,Хет-трик,Хет-трик од асистенции,...,Пенали,Спасени пенали,Победи,% на победи,Порази,% на порази,Играч на натпреварот,Номинации за играч на месец,Играч на месец,Гол на месецот
0,1,Дацо,D/GK,36,5,11,16,0.44,0,0,...,0/0,0/1,13,36%,16,44%,3,1,1,0
1,2,Лео,D/GK,34,40,19,59,1.74,3,3,...,0/1,1/2,12,35%,16,47%,3,2,3,1
2,3,Симиќ,AM,34,10,24,34,1.00,0,1,...,0/0,0/0,14,41%,16,47%,0,1,0,0
3,4,Стеф,M/GK,32,22,12,34,1.06,2,0,...,0/1,1/1,14,44%,12,38%,2,2,0,0
4,5,Нено,D/GK,29,0,6,6,0.21,0,0,...,0/1,1/3,11,38%,12,41%,0,2,0,0

In [261]:
CYRILLIC_TO_LATIN_MAP = {
    'А': 'A', 'а': 'a',
    'Б': 'B', 'б': 'b',
    'В': 'V', 'в': 'v',
    'Г': 'G', 'г': 'g',
    'Д': 'D', 'д': 'd',
    'Ѓ': 'Gj', 'ѓ': 'gj',
    'Е': 'E', 'е': 'e',
    'Ж': 'Zh', 'ж': 'zh',
    'З': 'Z', 'з': 'z',
    'И': 'I', 'и': 'i',
    'Ј': 'J', 'ј': 'j',
    'К': 'K', 'к': 'k',
    'Л': 'L', 'л': 'l',
    'Љ': 'Lj', 'љ': 'lj',
    'М': 'M', 'м': 'm',
    'Н': 'N', 'н': 'n',
    'Њ': 'Nj', 'њ': 'nj',
    'О': 'O', 'о': 'o',
    'П': 'P', 'п': 'p',
    'Р': 'R', 'р': 'r',
    'С': 'S', 'с': 's',
    'Т': 'T', 'т': 't',
    'Ќ': 'Kj', 'ќ': 'kj',
    'У': 'U', 'у': 'u',
    'Ф': 'F', 'ф': 'f',
    'Х': 'H', 'х': 'h',
    'Ц': 'C', 'ц': 'c',
    'Ч': 'Ch', 'ч': 'ch',
    'Џ': 'Dzh', 'џ': 'dzh',
    'Ш': 'Sh', 'ш': 'sh'
}
def cyrillicToLatinName(nameCyrillic):
    return ''.join(CYRILLIC_TO_LATIN_MAP.get(char, char) for char in nameCyrillic)

In [262]:
df = df.copy()

In [263]:
columns = df.columns.tolist()
columns

['Број на играчи',
 'Име',
 'Позиција',
 'Број на натпревари',
 'Голови',
 'Асистенции',
 'Г/А',
 'Г/А на натпревар',
 'Хет-трик ',
 'Хет-трик од асистенции',
 'Автоголови',
 'Слободни',
 'Пенали',
 'Спасени пенали ',
 'Победи',
 '% на победи',
 'Порази',
 '% на порази',
 'Играч на натпреварот',
 'Номинации за играч на месец',
 'Играч на месец',
 'Гол на месецот']

In [264]:
columns_translating_mk_to_en = {
'Број на играчи' : 'index',
 'Име':'name',
 'Позиција':'position',
 'Број на натпревари':'matches',
 'Голови':'goals',
 'Асистенции':'assists',
 'Г/А':'goal_contribution',
 'Г/А на натпревар':'gc_per_match',
 'Хет-трик ':'hat-trick',
 'Хет-трик од асистенции':'hat-trick-assists',
 'Автоголови':'owngoals',
 'Слободни':'freekicks',
 'Пенали':'penalty_stats',
 'Спасени пенали ':'penalty_saves',
 'Победи':'w',
 '% на победи':'w_percentage',
 'Порази':'losses',
 '% на порази':'loss_percentage',
 'Играч на натпреварот':'motm',
 'Номинации за играч на месец':'nominations',
 'Играч на месец':'potm',
 'Гол на месецот':'gotm'
}

In [265]:
columns = [columns_translating_mk_to_en.get(col) for col in columns]

In [266]:
columns

['index',
 'name',
 'position',
 'matches',
 'goals',
 'assists',
 'goal_contribution',
 'gc_per_match',
 'hat-trick',
 'hat-trick-assists',
 'owngoals',
 'freekicks',
 'penalty_stats',
 'penalty_saves',
 'w',
 'w_percentage',
 'losses',
 'loss_percentage',
 'motm',
 'nominations',
 'potm',
 'gotm']

In [267]:
df.columns = columns

In [268]:
df

,index,name,position,matches,goals,assists,goal_contribution,gc_per_match,hat-trick,hat-trick-assists,...,penalty_stats,penalty_saves,w,w_percentage,losses,loss_percentage,motm,nominations,potm,gotm
0,1,Дацо,D/GK,36,5,11,16,0.44,0,0,...,0/0,0/1,13,36%,16,44%,3,1,1,0
1,2,Лео,D/GK,34,40,19,59,1.74,3,3,...,0/1,1/2,12,35%,16,47%,3,2,3,1
2,3,Симиќ,AM,34,10,24,34,1.00,0,1,...,0/0,0/0,14,41%,16,47%,0,1,0,0
3,4,Стеф,M/GK,32,22,12,34,1.06,2,0,...,0/1,1/1,14,44%,12,38%,2,2,0,0
4,5,Нено,D/GK,29,0,6,6,0.21,0,0,...,0/1,1/3,11,38%,12,41%,0,2,0,0
5,6,Прем,A,27,38,19,57,2.11,7,0,...,1/1,0/0,11,41%,13,48%,3,2,0,4
6,7,Борјан,M/GK,27,31,19,50,1.85,4,1,...,0/1,0/0,17,63%,8,30%,0,0,1,0
7,8,Анчо,D,27,2,0,2,0.07,0,0,...,0/0,0/0,10,37%,13,48%,0,0,0,0
8,9,Хито,M,26,57,22,79,3.04,10,2,...,1/1,0/0,12,46%,10,38%,5,3,1,2
9,10,Христијан,D,25,14,21,35,1.40,0,1,...,0/1,0/0,13,52%,7,28%,1,1,1,0
10,11,Маки,D/GK,23,9,16,25,1.09,0,1,...,0/0,1/2,12,52%,7,30%,4,4,1,0
11,12,Џокер,A,22,24,14,38,1.73,1,1,...,0/0,0/0,7,32%,10,45%,1,0,0,0
12,13,Грекос,DM,22,7,5,12,0.55,0,0,...,0/1,0/0,5,23%,13,59%,0,0,0,0
13,14,Бале,D,13,2,2,4,0.31,0,0,...,0/0,0/0,3,23%,5,38%,1,0,0,0
14,15,Марио,М,11,13,8,21,1.91,0,0,...,0/0,0/0,6,55%,3,27%,3,0,0,0
15,16,Стец,GK,11,0,1,1,0.09,0,0,...,0/0,0/1,6,55%,4,36%,2,0,0,0
16,17,Даре,AM,10,11,9,20,2.00,1,1,...,0/0,0/0,3,30%,4,40%,3,1,0,0
17,18,Лазо,A,9,10,7,17,1.89,1,0,...,1/2,0/0,3,33%,2,22%,1,0,0,1
18,19,Мартин,М,9,9,7,16,1.78,2,0,...,0/0,0/0,3,33%,5,56%,4,0,0,0
19,20,Фич,A/GK,8,2,1,3,0.38,0,0,...,0/0,0/0,2,25%,5,63%,0,0,0,0
20,21,Нарго,АМ,4,4,3,7,1.75,0,0,...,0/0,0/0,1,25%,3,75%,0,0,0,0
21,22,Нух,GK,4,0,1,1,0.25,0,0,...,0/0,0/0,2,50%,2,50%,0,0,0,0
22,23,Филип,AM,4,1,0,1,0.25,0,0,...,0/0,0/0,2,50%,2,50%,0,0,0,0
23,24,Вуле,АМ,3,8,6,14,4.67,1,1,...,0/0,0/0,3,100%,0,0%,3,0,0,0
24,25,Јанчо,M,3,3,5,8,2.67,0,1,...,0/0,0/0,1,33%,1,33%,0,0,0,0
25,26,Давиде,М,3,2,3,5,1.67,0,0,...,0/0,0/0,0,0%,2,67%,0,0,0,0
26,27,Никец,AM,2,1,2,3,1.50,0,0,...,0/0,0/0,1,50%,0,0%,0,0,0,0
27,28,Фишбои,GK,2,0,0,0,0.00,0,0,...,0/0,0/0,1,50%,1,50%,0,0,0,0
28,29,Силбо,GK,2,0,0,0,0.00,0,0,...,0/0,0/0,1,50%,0,0%,1,0,0,0
29,30,Тео,AM,2,0,0,0,0.00,0,0,...,0/0,0/0,1,50%,0,0%,0,0,0,0
30,31,Горјан,DM,2,0,0,0,0.00,0,0,...,0/0,0/0,1,50%,1,50%,0,0,0,0
31,32,Тхео,М,1,4,2,6,6.00,1,0,...,0/0,0/0,1,100%,0,0%,0,0,0,0
32,33,Николче,АМ,1,2,2,4,4.00,0,0,...,0/0,0/0,0,0%,1,100%,0,0,0,0
33,34,Бодан,А,1,0,3,3,3.00,0,1,...,0/0,0/0,0,0%,1,100%,0,0,0,0
34,35,Ѓозо,М,1,2,1,3,3.00,0,0,...,0/0,0/0,1,100%,0,0%,0,0,0,0
35,36,Гаштар,АМ,1,1,1,2,2.00,0,0,...,0/0,0/0,1,100%,0,0%,0,0,0,0
36,37,Томас,А,1,2,0,2,2.00,0,0,...,0/0,0/0,0,0%,0,0%,0,0,0,0
37,38,Јан,A,1,1,1,2,2.00,0,0,...,0/0,0/0,0,0%,0,0%,0,0,0,0
38,39,Стефан,D,1,1,0,1,1.00,0,0,...,0/0,0/0,1,100%,0,0%,0,0,0,0
39,40,Рон,M,1,1,0,1,1.00,0,0,...,0/0,0/0,1,100%,0,0%,0,0,0,0
40,41,Димов,М,1,0,1,1,1.00,0,0,...,0/0,0/0,0,0%,1,100%,0,0,0,0
41,42,Хрис,М,1,0,0,0,0.00,0,0,...,0/0,0/0,0,0%,1,100%,0,0,0,0
42,43,Леон,М,1,0,0,0,0.00,0,0,...,0/0,0/0,0,0%,0,0%,0,0,0,0
43,44,Тер Стеген,M/GK,1,0,0,0,0.00,0,0,...,0/0,0/0,0,0%,0,0%,0,0,0,0

In [269]:
split_positions = df['position'].str.split('/', expand=True)
df['position'] = split_positions[0]
df.insert(3, 'secondary_position', split_positions[1])

In [270]:
df

,index,name,position,secondary_position,matches,goals,assists,goal_contribution,gc_per_match,hat-trick,...,penalty_stats,penalty_saves,w,w_percentage,losses,loss_percentage,motm,nominations,potm,gotm
0,1,Дацо,D,GK,36,5,11,16,0.44,0,...,0/0,0/1,13,36%,16,44%,3,1,1,0
1,2,Лео,D,GK,34,40,19,59,1.74,3,...,0/1,1/2,12,35%,16,47%,3,2,3,1
2,3,Симиќ,AM,None,34,10,24,34,1.00,0,...,0/0,0/0,14,41%,16,47%,0,1,0,0
3,4,Стеф,M,GK,32,22,12,34,1.06,2,...,0/1,1/1,14,44%,12,38%,2,2,0,0
4,5,Нено,D,GK,29,0,6,6,0.21,0,...,0/1,1/3,11,38%,12,41%,0,2,0,0
5,6,Прем,A,None,27,38,19,57,2.11,7,...,1/1,0/0,11,41%,13,48%,3,2,0,4
6,7,Борјан,M,GK,27,31,19,50,1.85,4,...,0/1,0/0,17,63%,8,30%,0,0,1,0
7,8,Анчо,D,None,27,2,0,2,0.07,0,...,0/0,0/0,10,37%,13,48%,0,0,0,0
8,9,Хито,M,None,26,57,22,79,3.04,10,...,1/1,0/0,12,46%,10,38%,5,3,1,2
9,10,Христијан,D,None,25,14,21,35,1.40,0,...,0/1,0/0,13,52%,7,28%,1,1,1,0
10,11,Маки,D,GK,23,9,16,25,1.09,0,...,0/0,1/2,12,52%,7,30%,4,4,1,0
11,12,Џокер,A,None,22,24,14,38,1.73,1,...,0/0,0/0,7,32%,10,45%,1,0,0,0
12,13,Грекос,DM,None,22,7,5,12,0.55,0,...,0/1,0/0,5,23%,13,59%,0,0,0,0
13,14,Бале,D,None,13,2,2,4,0.31,0,...,0/0,0/0,3,23%,5,38%,1,0,0,0
14,15,Марио,М,None,11,13,8,21,1.91,0,...,0/0,0/0,6,55%,3,27%,3,0,0,0
15,16,Стец,GK,None,11,0,1,1,0.09,0,...,0/0,0/1,6,55%,4,36%,2,0,0,0
16,17,Даре,AM,None,10,11,9,20,2.00,1,...,0/0,0/0,3,30%,4,40%,3,1,0,0
17,18,Лазо,A,None,9,10,7,17,1.89,1,...,1/2,0/0,3,33%,2,22%,1,0,0,1
18,19,Мартин,М,None,9,9,7,16,1.78,2,...,0/0,0/0,3,33%,5,56%,4,0,0,0
19,20,Фич,A,GK,8,2,1,3,0.38,0,...,0/0,0/0,2,25%,5,63%,0,0,0,0
20,21,Нарго,АМ,None,4,4,3,7,1.75,0,...,0/0,0/0,1,25%,3,75%,0,0,0,0
21,22,Нух,GK,None,4,0,1,1,0.25,0,...,0/0,0/0,2,50%,2,50%,0,0,0,0
22,23,Филип,AM,None,4,1,0,1,0.25,0,...,0/0,0/0,2,50%,2,50%,0,0,0,0
23,24,Вуле,АМ,None,3,8,6,14,4.67,1,...,0/0,0/0,3,100%,0,0%,3,0,0,0
24,25,Јанчо,M,None,3,3,5,8,2.67,0,...,0/0,0/0,1,33%,1,33%,0,0,0,0
25,26,Давиде,М,None,3,2,3,5,1.67,0,...,0/0,0/0,0,0%,2,67%,0,0,0,0
26,27,Никец,AM,None,2,1,2,3,1.50,0,...,0/0,0/0,1,50%,0,0%,0,0,0,0
27,28,Фишбои,GK,None,2,0,0,0,0.00,0,...,0/0,0/0,1,50%,1,50%,0,0,0,0
28,29,Силбо,GK,None,2,0,0,0,0.00,0,...,0/0,0/0,1,50%,0,0%,1,0,0,0
29,30,Тео,AM,None,2,0,0,0,0.00,0,...,0/0,0/0,1,50%,0,0%,0,0,0,0
30,31,Горјан,DM,None,2,0,0,0,0.00,0,...,0/0,0/0,1,50%,1,50%,0,0,0,0
31,32,Тхео,М,None,1,4,2,6,6.00,1,...,0/0,0/0,1,100%,0,0%,0,0,0,0
32,33,Николче,АМ,None,1,2,2,4,4.00,0,...,0/0,0/0,0,0%,1,100%,0,0,0,0
33,34,Бодан,А,None,1,0,3,3,3.00,0,...,0/0,0/0,0,0%,1,100%,0,0,0,0
34,35,Ѓозо,М,None,1,2,1,3,3.00,0,...,0/0,0/0,1,100%,0,0%,0,0,0,0
35,36,Гаштар,АМ,None,1,1,1,2,2.00,0,...,0/0,0/0,1,100%,0,0%,0,0,0,0
36,37,Томас,А,None,1,2,0,2,2.00,0,...,0/0,0/0,0,0%,0,0%,0,0,0,0
37,38,Јан,A,None,1,1,1,2,2.00,0,...,0/0,0/0,0,0%,0,0%,0,0,0,0
38,39,Стефан,D,None,1,1,0,1,1.00,0,...,0/0,0/0,1,100%,0,0%,0,0,0,0
39,40,Рон,M,None,1,1,0,1,1.00,0,...,0/0,0/0,1,100%,0,0%,0,0,0,0
40,41,Димов,М,None,1,0,1,1,1.00,0,...,0/0,0/0,0,0%,1,100%,0,0,0,0
41,42,Хрис,М,None,1,0,0,0,0.00,0,...,0/0,0/0,0,0%,1,100%,0,0,0,0
42,43,Леон,М,None,1,0,0,0,0.00,0,...,0/0,0/0,0,0%,0,0%,0,0,0,0
43,44,Тер Стеген,M,GK,1,0,0,0,0.00,0,...,0/0,0/0,0,0%,0,0%,0,0,0,0

In [271]:
df['loss_percentage'] = df['loss_percentage'].str.replace('%', '')
df['loss_percentage'] = df['loss_percentage'].astype(float) / 100
df['loss_percentage'] = df['loss_percentage'].round(decimals=2)

In [272]:
df['w_percentage'] = df['w_percentage'].str.replace('%', '')
df['w_percentage'] = df['w_percentage'].astype(float) / 100
df['w_percentage'] = df['w_percentage'].round(decimals=2)

In [273]:
df['name'] = df['name'].apply(cyrillicToLatinName)

In [274]:
df #inspect before save

,index,name,position,secondary_position,matches,goals,assists,goal_contribution,gc_per_match,hat-trick,...,penalty_stats,penalty_saves,w,w_percentage,losses,loss_percentage,motm,nominations,potm,gotm
0,1,Daco,D,GK,36,5,11,16,0.44,0,...,0/0,0/1,13,0.36,16,0.44,3,1,1,0
1,2,Leo,D,GK,34,40,19,59,1.74,3,...,0/1,1/2,12,0.35,16,0.47,3,2,3,1
2,3,Simikj,AM,None,34,10,24,34,1.00,0,...,0/0,0/0,14,0.41,16,0.47,0,1,0,0
3,4,Stef,M,GK,32,22,12,34,1.06,2,...,0/1,1/1,14,0.44,12,0.38,2,2,0,0
4,5,Neno,D,GK,29,0,6,6,0.21,0,...,0/1,1/3,11,0.38,12,0.41,0,2,0,0
5,6,Prem,A,None,27,38,19,57,2.11,7,...,1/1,0/0,11,0.41,13,0.48,3,2,0,4
6,7,Borjan,M,GK,27,31,19,50,1.85,4,...,0/1,0/0,17,0.63,8,0.30,0,0,1,0
7,8,Ancho,D,None,27,2,0,2,0.07,0,...,0/0,0/0,10,0.37,13,0.48,0,0,0,0
8,9,Hito,M,None,26,57,22,79,3.04,10,...,1/1,0/0,12,0.46,10,0.38,5,3,1,2
9,10,Hristijan,D,None,25,14,21,35,1.40,0,...,0/1,0/0,13,0.52,7,0.28,1,1,1,0
10,11,Maki,D,GK,23,9,16,25,1.09,0,...,0/0,1/2,12,0.52,7,0.30,4,4,1,0
11,12,Dzhoker,A,None,22,24,14,38,1.73,1,...,0/0,0/0,7,0.32,10,0.45,1,0,0,0
12,13,Grekos,DM,None,22,7,5,12,0.55,0,...,0/1,0/0,5,0.23,13,0.59,0,0,0,0
13,14,Bale,D,None,13,2,2,4,0.31,0,...,0/0,0/0,3,0.23,5,0.38,1,0,0,0
14,15,Mario,М,None,11,13,8,21,1.91,0,...,0/0,0/0,6,0.55,3,0.27,3,0,0,0
15,16,Stec,GK,None,11,0,1,1,0.09,0,...,0/0,0/1,6,0.55,4,0.36,2,0,0,0
16,17,Dare,AM,None,10,11,9,20,2.00,1,...,0/0,0/0,3,0.30,4,0.40,3,1,0,0
17,18,Lazo,A,None,9,10,7,17,1.89,1,...,1/2,0/0,3,0.33,2,0.22,1,0,0,1
18,19,Martin,М,None,9,9,7,16,1.78,2,...,0/0,0/0,3,0.33,5,0.56,4,0,0,0
19,20,Fich,A,GK,8,2,1,3,0.38,0,...,0/0,0/0,2,0.25,5,0.63,0,0,0,0
20,21,Nargo,АМ,None,4,4,3,7,1.75,0,...,0/0,0/0,1,0.25,3,0.75,0,0,0,0
21,22,Nuh,GK,None,4,0,1,1,0.25,0,...,0/0,0/0,2,0.50,2,0.50,0,0,0,0
22,23,Filip,AM,None,4,1,0,1,0.25,0,...,0/0,0/0,2,0.50,2,0.50,0,0,0,0
23,24,Vule,АМ,None,3,8,6,14,4.67,1,...,0/0,0/0,3,1.00,0,0.00,3,0,0,0
24,25,Jancho,M,None,3,3,5,8,2.67,0,...,0/0,0/0,1,0.33,1,0.33,0,0,0,0
25,26,Davide,М,None,3,2,3,5,1.67,0,...,0/0,0/0,0,0.00,2,0.67,0,0,0,0
26,27,Nikec,AM,None,2,1,2,3,1.50,0,...,0/0,0/0,1,0.50,0,0.00,0,0,0,0
27,28,Fishboi,GK,None,2,0,0,0,0.00,0,...,0/0,0/0,1,0.50,1,0.50,0,0,0,0
28,29,Silbo,GK,None,2,0,0,0,0.00,0,...,0/0,0/0,1,0.50,0,0.00,1,0,0,0
29,30,Teo,AM,None,2,0,0,0,0.00,0,...,0/0,0/0,1,0.50,0,0.00,0,0,0,0
30,31,Gorjan,DM,None,2,0,0,0,0.00,0,...,0/0,0/0,1,0.50,1,0.50,0,0,0,0
31,32,Theo,М,None,1,4,2,6,6.00,1,...,0/0,0/0,1,1.00,0,0.00,0,0,0,0
32,33,Nikolche,АМ,None,1,2,2,4,4.00,0,...,0/0,0/0,0,0.00,1,1.00,0,0,0,0
33,34,Bodan,А,None,1,0,3,3,3.00,0,...,0/0,0/0,0,0.00,1,1.00,0,0,0,0
34,35,Gjozo,М,None,1,2,1,3,3.00,0,...,0/0,0/0,1,1.00,0,0.00,0,0,0,0
35,36,Gashtar,АМ,None,1,1,1,2,2.00,0,...,0/0,0/0,1,1.00,0,0.00,0,0,0,0
36,37,Tomas,А,None,1,2,0,2,2.00,0,...,0/0,0/0,0,0.00,0,0.00,0,0,0,0
37,38,Jan,A,None,1,1,1,2,2.00,0,...,0/0,0/0,0,0.00,0,0.00,0,0,0,0
38,39,Stefan,D,None,1,1,0,1,1.00,0,...,0/0,0/0,1,1.00,0,0.00,0,0,0,0
39,40,Ron,M,None,1,1,0,1,1.00,0,...,0/0,0/0,1,1.00,0,0.00,0,0,0,0
40,41,Dimov,М,None,1,0,1,1,1.00,0,...,0/0,0/0,0,0.00,1,1.00,0,0,0,0
41,42,Hris,М,None,1,0,0,0,0.00,0,...,0/0,0/0,0,0.00,1,1.00,0,0,0,0
42,43,Leon,М,None,1,0,0,0,0.00,0,...,0/0,0/0,0,0.00,0,0.00,0,0,0,0
43,44,Ter Stegen,M,GK,1,0,0,0,0.00,0,...,0/0,0/0,0,0.00,0,0.00,0,0,0,0

In [275]:
df.to_csv('zoki_liga_formatted.csv',index=False)

In [276]:
df_final = pd.read_csv('zoki_liga_final.csv')
df_test = pd.read_csv('zoki_liga.csv')
df_formatted = pd.read_csv('zoki_liga_formatted.csv')
#for test

In [277]:
# df_formatted.loc[df['secondary_position'].isna(), 'secondary_position'] = 'No Secondary Position'

In [278]:
# df_formatted

In [279]:
ratings_file_path = 'ratings/*.xlsx'
list_of_files = glob.glob(ratings_file_path)
print(list_of_files)

['ratings\\andrej_anakiev.xlsx', 'ratings\\borjan_todorovski.xlsx', 'ratings\\ivan_kuzmanovski.xlsx']

In [280]:
dataframes = []
for excel in list_of_files:
    df = pd.read_excel(excel)
    dataframes.append(df)

ID_COL = "name"
df_all = pd.concat(dataframes)
rating_cols = [c for c in df_all.columns if c not in {"index", "name"}]

#Average
df_avg = df_all.groupby(["index", "name"])[rating_cols].mean().round(2).sort_values("index")
#Mode
def first_mode(s: pd.Series): #mode
    m = s.mode(dropna=True)
    return m.iloc[0] if not m.empty else np.nan
df_mode = df_all.groupby(["index", "name"], as_index=False)[rating_cols].agg(first_mode).sort_values("index")

In [281]:
df_avg.to_csv("df_mean.csv", index=False)
df_mode.to_csv("df_mode.csv", index=False)

In [282]:
df_mode

,index,name,interceptions_overall_ability,fouls_commiting,stamina_rating,positions_played,leadership_measure,passing,physical,gk_ability,skill,positioning_sense
0,1,Daco,5.0,1.0,5.0,5.0,3.0,5.0,5.0,9.0,3.0,4.0
1,2,Leo,8.0,2.0,9.0,10.0,3.0,9.0,9.0,6.0,7.0,8.0
2,3,Simikj,4.0,1.0,3.0,4.0,2.0,8.0,3.0,1.0,8.0,6.0
3,4,Stef,3.0,3.0,4.0,3.0,4.0,3.0,2.0,2.0,2.0,4.0
4,5,Neno,2.0,7.0,5.0,2.0,1.0,2.0,7.0,7.0,2.0,2.0
5,6,Prem,6.0,2.0,6.0,6.0,6.0,7.0,6.0,1.0,8.0,8.0
6,7,Borjan,5.0,3.0,4.0,3.0,3.0,5.0,7.0,6.0,5.0,7.0
7,8,Ancho,3.0,1.0,6.0,2.0,2.0,2.0,3.0,1.0,2.0,5.0
8,9,Hito,8.0,10.0,7.0,5.0,5.0,8.0,6.0,1.0,8.0,9.0
9,10,Hristijan,4.0,4.0,3.0,4.0,1.0,3.0,7.0,1.0,4.0,4.0
10,11,Maki,7.0,3.0,7.0,8.0,4.0,6.0,4.0,1.0,6.0,7.0
11,12,Dzhoker,6.0,1.0,5.0,3.0,2.0,7.0,5.0,1.0,7.0,7.0
12,13,Grekos,2.0,1.0,5.0,5.0,1.0,4.0,2.0,1.0,3.0,5.0
13,14,Bale,6.0,2.0,3.0,2.0,3.0,3.0,7.0,1.0,3.0,4.0
14,15,Mario,7.0,3.0,8.0,3.0,4.0,8.0,6.0,1.0,8.0,8.0
15,16,Stec,1.0,1.0,1.0,1.0,1.0,2.0,1.0,6.0,1.0,1.0
16,17,Dare,5.0,2.0,5.0,4.0,1.0,6.0,3.0,1.0,8.0,8.0
17,18,Lazo,4.0,8.0,7.0,5.0,3.0,4.0,8.0,1.0,5.0,4.0
18,19,Martin,9.0,4.0,8.0,6.0,7.0,9.0,9.0,1.0,9.0,9.0
19,20,Fich,7.0,5.0,5.0,4.0,1.0,6.0,5.0,8.0,3.0,6.0
20,21,Nargo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,Nuh,1.0,1.0,1.0,1.0,2.0,2.0,3.0,6.0,2.0,1.0
22,23,Filip,4.0,2.0,3.0,3.0,2.0,3.0,3.0,1.0,3.0,5.0
23,24,Vule,7.0,3.0,8.0,4.0,6.0,7.0,10.0,1.0,9.0,8.0
24,25,Jancho,7.0,7.0,6.0,6.0,1.0,7.0,6.0,1.0,7.0,7.0
25,26,Davide,7.0,5.0,6.0,6.0,4.0,8.0,6.0,1.0,8.0,7.0
26,27,Nikec,4.0,3.0,7.0,4.0,4.0,5.0,4.0,1.0,5.0,4.0
27,28,Fishboi,2.0,1.0,2.0,2.0,1.0,2.0,1.0,2.0,1.0,1.0
28,29,Silbo,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.0,1.0,1.0
29,30,Teo,7.0,4.0,5.0,5.0,4.0,7.0,5.0,1.0,7.0,7.0
30,31,Gorjan,6.0,3.0,4.0,4.0,4.0,5.0,5.0,1.0,4.0,5.0
31,32,Theo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,Nikolche,4.0,2.0,4.0,3.0,4.0,4.0,4.0,1.0,3.0,4.0
33,34,Bodan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35,Gjozo,7.0,5.0,7.0,5.0,4.0,7.0,6.0,1.0,7.0,6.0
35,36,Gashtar,6.0,9.0,7.0,6.0,4.0,7.0,7.0,1.0,7.0,6.0
36,37,Tomas,7.0,6.0,7.0,7.0,3.0,7.0,8.0,1.0,8.0,7.0
37,38,Jan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,Stefan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,Ron,7.0,4.0,7.0,6.0,4.0,6.0,6.0,1.0,7.0,7.0
40,41,Dimov,6.0,4.0,6.0,4.0,4.0,5.0,5.0,1.0,5.0,5.0
41,42,Hris,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,Leon,5.0,4.0,5.0,4.0,4.0,6.0,6.0,1.0,5.0,5.0
43,44,Ter Stegen,5.0,1.0,6.0,3.0,2.0,4.0,7.0,8.0,5.0,5.0

In [283]:
df_avg

,,interceptions_overall_ability,fouls_commiting,stamina_rating,positions_played,leadership_measure,passing,physical,gk_ability,skill,positioning_sense
index,name,,,,,,,,,,
1,Daco,5.33,4.00,5.33,5.33,3.67,4.33,6.00,9.33,3.33,5.33
2,Leo,8.33,4.33,8.67,9.33,6.67,8.33,8.67,7.00,8.00,8.33
3,Simikj,5.67,3.33,4.00,4.00,3.00,7.67,2.33,1.00,7.67,7.00
4,Stef,4.67,2.33,5.00,5.33,5.33,4.33,5.00,5.00,4.00,5.00
5,Neno,3.00,8.00,5.33,3.00,1.00,3.67,6.33,7.67,3.00,2.67
6,Prem,7.00,3.00,6.00,5.33,6.33,7.33,7.00,2.67,8.33,8.00
7,Borjan,4.67,3.33,5.67,4.33,4.67,5.00,7.67,4.33,5.33,7.33
8,Ancho,3.67,5.33,5.00,2.00,3.00,2.33,3.33,1.33,2.33,4.33
9,Hito,8.33,8.67,8.67,5.33,6.00,7.67,7.67,2.67,8.33,8.33
10,Hristijan,6.00,3.33,4.00,5.00,4.67,6.00,7.33,2.33,5.33,6.33
11,Maki,8.00,2.33,8.33,7.67,7.00,7.33,5.00,5.00,7.00,8.00
12,Dzhoker,6.00,2.00,6.33,4.00,2.67,6.67,4.67,2.33,6.67,7.33
13,Grekos,4.00,3.33,6.00,4.67,2.33,5.00,3.00,2.00,4.00,5.33
14,Bale,5.67,3.67,4.00,3.00,7.33,4.33,8.33,3.33,3.33,5.67
15,Mario,8.00,6.00,7.67,5.33,6.33,7.67,6.33,2.67,7.33,8.00
16,Stec,1.00,1.00,2.33,1.00,1.33,3.67,1.67,7.67,1.33,3.00
17,Dare,7.33,2.33,6.00,5.67,2.67,7.67,4.33,2.33,6.67,7.33
18,Lazo,5.00,6.00,6.33,5.33,2.67,5.33,7.67,2.33,6.00,5.67
19,Martin,8.33,3.00,8.33,8.00,7.67,8.67,8.33,3.67,9.00,8.67
20,Fich,5.67,3.67,6.00,6.00,3.33,6.33,6.67,8.67,5.33,5.33
21,Nargo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Nuh,1.33,1.00,2.67,1.00,3.00,3.67,2.67,7.33,1.67,2.33
23,Filip,4.00,2.50,3.00,3.50,2.00,4.00,3.50,2.50,3.50,5.50
24,Vule,8.67,2.33,9.00,7.33,7.67,8.33,9.67,3.67,9.33,9.00
25,Jancho,7.00,7.00,6.00,6.00,1.00,7.00,6.00,1.00,7.00,7.00
26,Davide,7.50,6.00,6.50,6.50,5.00,8.00,6.50,1.00,8.50,7.00
27,Nikec,4.00,3.00,7.00,4.00,4.00,5.00,4.00,1.00,5.00,4.00
28,Fishboi,1.67,2.67,2.67,2.33,1.00,1.67,1.33,2.33,1.33,1.50
29,Silbo,1.00,1.00,1.00,1.00,1.00,1.00,1.00,8.00,1.00,1.00
30,Teo,7.00,4.00,5.00,5.00,4.00,7.00,5.00,1.00,7.00,7.00
31,Gorjan,6.00,3.00,4.00,4.00,4.00,5.00,5.00,1.00,4.00,5.00
32,Theo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Nikolche,4.00,2.00,4.00,3.00,4.00,4.00,4.00,1.00,3.00,4.00
34,Bodan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Gjozo,7.00,5.00,7.00,5.00,4.00,7.00,6.00,1.00,7.00,6.00
36,Gashtar,6.00,9.00,7.00,6.00,4.00,7.00,7.00,1.00,7.00,6.00
37,Tomas,7.00,6.00,7.00,7.00,3.00,7.00,8.00,1.00,8.00,7.00
38,Jan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Stefan,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Ron,7.00,4.00,7.00,6.00,4.00,6.00,6.00,1.00,7.00,7.00
41,Dimov,6.00,4.00,6.00,4.00,4.00,5.00,5.00,1.00,5.00,5.00
42,Hris,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Leon,5.00,4.00,5.00,4.00,4.00,6.00,6.00,1.00,5.00,5.00
44,Ter Stegen,5.00,3.50,7.00,3.50,3.00,5.00,8.00,8.00,5.50,5.50

In [284]:
df_combined = pd.concat([df_formatted.reset_index(drop=True),df_avg.reset_index(drop=True)], axis=1)

In [285]:
df_combined

,index,name,position,secondary_position,matches,goals,assists,goal_contribution,gc_per_match,hat-trick,...,interceptions_overall_ability,fouls_commiting,stamina_rating,positions_played,leadership_measure,passing,physical,gk_ability,skill,positioning_sense
0,1,Daco,D,GK,36,5,11,16,0.44,0,...,5.33,4.00,5.33,5.33,3.67,4.33,6.00,9.33,3.33,5.33
1,2,Leo,D,GK,34,40,19,59,1.74,3,...,8.33,4.33,8.67,9.33,6.67,8.33,8.67,7.00,8.00,8.33
2,3,Simikj,AM,NaN,34,10,24,34,1.00,0,...,5.67,3.33,4.00,4.00,3.00,7.67,2.33,1.00,7.67,7.00
3,4,Stef,M,GK,32,22,12,34,1.06,2,...,4.67,2.33,5.00,5.33,5.33,4.33,5.00,5.00,4.00,5.00
4,5,Neno,D,GK,29,0,6,6,0.21,0,...,3.00,8.00,5.33,3.00,1.00,3.67,6.33,7.67,3.00,2.67
5,6,Prem,A,NaN,27,38,19,57,2.11,7,...,7.00,3.00,6.00,5.33,6.33,7.33,7.00,2.67,8.33,8.00
6,7,Borjan,M,GK,27,31,19,50,1.85,4,...,4.67,3.33,5.67,4.33,4.67,5.00,7.67,4.33,5.33,7.33
7,8,Ancho,D,NaN,27,2,0,2,0.07,0,...,3.67,5.33,5.00,2.00,3.00,2.33,3.33,1.33,2.33,4.33
8,9,Hito,M,NaN,26,57,22,79,3.04,10,...,8.33,8.67,8.67,5.33,6.00,7.67,7.67,2.67,8.33,8.33
9,10,Hristijan,D,NaN,25,14,21,35,1.40,0,...,6.00,3.33,4.00,5.00,4.67,6.00,7.33,2.33,5.33,6.33
10,11,Maki,D,GK,23,9,16,25,1.09,0,...,8.00,2.33,8.33,7.67,7.00,7.33,5.00,5.00,7.00,8.00
11,12,Dzhoker,A,NaN,22,24,14,38,1.73,1,...,6.00,2.00,6.33,4.00,2.67,6.67,4.67,2.33,6.67,7.33
12,13,Grekos,DM,NaN,22,7,5,12,0.55,0,...,4.00,3.33,6.00,4.67,2.33,5.00,3.00,2.00,4.00,5.33
13,14,Bale,D,NaN,13,2,2,4,0.31,0,...,5.67,3.67,4.00,3.00,7.33,4.33,8.33,3.33,3.33,5.67
14,15,Mario,М,NaN,11,13,8,21,1.91,0,...,8.00,6.00,7.67,5.33,6.33,7.67,6.33,2.67,7.33,8.00
15,16,Stec,GK,NaN,11,0,1,1,0.09,0,...,1.00,1.00,2.33,1.00,1.33,3.67,1.67,7.67,1.33,3.00
16,17,Dare,AM,NaN,10,11,9,20,2.00,1,...,7.33,2.33,6.00,5.67,2.67,7.67,4.33,2.33,6.67,7.33
17,18,Lazo,A,NaN,9,10,7,17,1.89,1,...,5.00,6.00,6.33,5.33,2.67,5.33,7.67,2.33,6.00,5.67
18,19,Martin,М,NaN,9,9,7,16,1.78,2,...,8.33,3.00,8.33,8.00,7.67,8.67,8.33,3.67,9.00,8.67
19,20,Fich,A,GK,8,2,1,3,0.38,0,...,5.67,3.67,6.00,6.00,3.33,6.33,6.67,8.67,5.33,5.33
20,21,Nargo,АМ,NaN,4,4,3,7,1.75,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,22,Nuh,GK,NaN,4,0,1,1,0.25,0,...,1.33,1.00,2.67,1.00,3.00,3.67,2.67,7.33,1.67,2.33
22,23,Filip,AM,NaN,4,1,0,1,0.25,0,...,4.00,2.50,3.00,3.50,2.00,4.00,3.50,2.50,3.50,5.50
23,24,Vule,АМ,NaN,3,8,6,14,4.67,1,...,8.67,2.33,9.00,7.33,7.67,8.33,9.67,3.67,9.33,9.00
24,25,Jancho,M,NaN,3,3,5,8,2.67,0,...,7.00,7.00,6.00,6.00,1.00,7.00,6.00,1.00,7.00,7.00
25,26,Davide,М,NaN,3,2,3,5,1.67,0,...,7.50,6.00,6.50,6.50,5.00,8.00,6.50,1.00,8.50,7.00
26,27,Nikec,AM,NaN,2,1,2,3,1.50,0,...,4.00,3.00,7.00,4.00,4.00,5.00,4.00,1.00,5.00,4.00
27,28,Fishboi,GK,NaN,2,0,0,0,0.00,0,...,1.67,2.67,2.67,2.33,1.00,1.67,1.33,2.33,1.33,1.50
28,29,Silbo,GK,NaN,2,0,0,0,0.00,0,...,1.00,1.00,1.00,1.00,1.00,1.00,1.00,8.00,1.00,1.00
29,30,Teo,AM,NaN,2,0,0,0,0.00,0,...,7.00,4.00,5.00,5.00,4.00,7.00,5.00,1.00,7.00,7.00
30,31,Gorjan,DM,NaN,2,0,0,0,0.00,0,...,6.00,3.00,4.00,4.00,4.00,5.00,5.00,1.00,4.00,5.00
31,32,Theo,М,NaN,1,4,2,6,6.00,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,33,Nikolche,АМ,NaN,1,2,2,4,4.00,0,...,4.00,2.00,4.00,3.00,4.00,4.00,4.00,1.00,3.00,4.00
33,34,Bodan,А,NaN,1,0,3,3,3.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,35,Gjozo,М,NaN,1,2,1,3,3.00,0,...,7.00,5.00,7.00,5.00,4.00,7.00,6.00,1.00,7.00,6.00
35,36,Gashtar,АМ,NaN,1,1,1,2,2.00,0,...,6.00,9.00,7.00,6.00,4.00,7.00,7.00,1.00,7.00,6.00
36,37,Tomas,А,NaN,1,2,0,2,2.00,0,...,7.00,6.00,7.00,7.00,3.00,7.00,8.00,1.00,8.00,7.00
37,38,Jan,A,NaN,1,1,1,2,2.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,39,Stefan,D,NaN,1,1,0,1,1.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,40,Ron,M,NaN,1,1,0,1,1.00,0,...,7.00,4.00,7.00,6.00,4.00,6.00,6.00,1.00,7.00,7.00
40,41,Dimov,М,NaN,1,0,1,1,1.00,0,...,6.00,4.00,6.00,4.00,4.00,5.00,5.00,1.00,5.00,5.00
41,42,Hris,М,NaN,1,0,0,0,0.00,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,43,Leon,М,NaN,1,0,0,0,0.00,0,...,5.00,4.00,5.00,4.00,4.00,6.00,6.00,1.00,5.00,5.00
43,44,Ter Stegen,M,GK,1,0,0,0,0.00,0,...,5.00,3.50,7.00,3.50,3.00,5.00,8.00,8.00,5.50,5.50

In [286]:
df_combined.to_csv("zoki_liga_formatted.csv", index=False)